project:
  type: website

output-dir: docs

website:
  title: "Adib Mazloom Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analytics.qmd
        text: Engineering Analytics
      - href: mba-projects.qmd
        text: MBA Projects
      - href: resume.qmd
        text: Resume
  page-navigation: true
  repo-url: "https://github.com/AdibMazloom/Mazloom-Adib-Website-Portfolio"
  repo-actions: [source]

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 2
    code-fold: true



